### PR TITLE
Migrate metadata module to JUnit 5

### PR DESCRIPTION
**Pull request by ijuma**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by rondagostino — APPROVED** [review]
LGTM

**Comment by rondagostino** [comment]
53 test failures, but they are unrelated.  53 is a worrisome number, though -- do we know what the deal is with those?

**Comment by ijuma** [comment]
There were a number of unrelated failures;

> kafka.network.DynamicConnectionQuotaTest.testDynamicListenerConnectionCreationRateQuota
> kafka.server.ControllerMutationQuotaTest.testPermissiveCreateTopicsRequest
> kafka.server.RequestQuotaTest.testUnauthorizedThrottle
> kafka.server.RequestQuotaTest.testUnthrottledClient
> kafka.server.RequestQuotaTest.testResponseThrottleTime
> kafka.server.KafkaApisTest.shouldReplaceProducerFencedWithInvalidProducerEpochInAddOffsetToTxnWithOlderClient
> kafka.server.KafkaApisTest.shouldRespondWithUnsupportedForMessageFormatOnHandleWriteTxnMarkersWhenMagicLowerThanRequired
> kafka.server.KafkaApisTest.testOffsetCommitWithInvalidPartition
> kafka.server.KafkaApisTest.testStopReplicaRequestWithNewerBrokerEpochIsValid
> kafka.server.KafkaApisTest.testListGroupsRequestWithState
> kafka.server.KafkaApisTest.testOffsetDeleteWithInvalidGroup
> kafka.server.KafkaApisTest.testListGroupsRequest
> kafka.server.KafkaApisTest.testJoinGroupWhenAnErrorOccurs
> kafka.server.KafkaApisTest.shouldReplaceProducerFencedWithInvalidProducerEpochInAddPartitionToTxnWithOlderClient
> kafka.server.KafkaApisTest.testSyncGroupProtocolTypeAndName
> kafka.server.KafkaApisTest.testReadUncommittedConsumerListOffsetLatest
> kafka.server.KafkaApisTest.testMetadataRequestOnDistinctListenerWithInconsistentListenersAcrossBrokers
> kafka.server.KafkaApisTest.testDescribeGroups
> kafka.server.KafkaApisTest.testLeaderReplicaIfLocalRaisesFencedLeaderEpoch
> kafka.server.KafkaApisTest.testStopReplicaRequestWithCurrentBrokerEpoch
> kafka.server.KafkaApisTest.testFetchRequestV9WithNoLogConfig
> kafka.server.KafkaApisTest.shouldRespondWithUnknownTopicWhenPartitionIsNotHosted
> kafka.server.KafkaApisTest.testJoinGroupProtocolType
> kafka.server.KafkaApisTest.testLeaderAndIsrRequestWithStaleBrokerEpochIsRejected
> kafka.server.KafkaApisTest.rejectSyncGroupRequestWhenStaticMembershipNotSupported
> kafka.server.KafkaApisTest.rejectHeartbeatRequestWhenStaticMembershipNotSupported
> kafka.server.KafkaApisTest.testAlterReplicaLogDirs
> kafka.server.KafkaApisTest.testReadCommittedConsumerListOffsetLatest
> kafka.server.KafkaApisTest.testSyncGroupProtocolTypeAndNameAreMandatorySinceV5
> kafka.server.KafkaApisTest.testMetadataRequestOnSharedListenerWithInconsistentListenersAcrossBrokers
> kafka.server.KafkaApisTest.testUpdateMetadataRequestWithCurrentBrokerEpoch
> kafka.server.KafkaApisTest.testAddPartitionsToTxnWithInvalidPartition
> kafka.server.KafkaApisTest.testOffsetDeleteWithInvalidPartition
> kafka.server.KafkaApisTest.shouldReplaceProducerFencedWithInvalidProducerEpochInEndTxnWithOlderClient
> kafka.server.KafkaApisTest.testLeaderReplicaIfLocalRaisesUnknownTopicOrPartition
> kafka.server.KafkaApisTest.testLeaderReplicaIfLocalRaisesNotLeaderOrFollower
> kafka.server.KafkaApisTest.testLeaderReplicaIfLocalRaisesUnknownLeaderEpoch
> kafka.server.KafkaApisTest.testOffsetDelete
> kafka.server.KafkaApisTest.testUpdateMetadataRequestWithStaleBrokerEpochIsRejected
> kafka.server.KafkaApisTest.testUpdateMetadataRequestWithNewerBrokerEpochIsValid
> kafka.server.KafkaApisTest.testTxnOffsetCommitWithInvalidPartition
> kafka.server.KafkaApisTest.testLeaderAndIsrRequestWithCurrentBrokerEpoch
> kafka.server.KafkaApisTest.testLeaderAndIsrRequestWithNewerBrokerEpochIsValid
> kafka.server.KafkaApisTest.rejectInitProducerIdWhenEpochButNotIdProvided
> kafka.server.KafkaApisTest.shouldReplaceCoordinatorNotAvailableWithLoadInProcessInTxnOffsetCommitWithOlderClient
> kafka.server.KafkaApisTest.shouldReplaceProducerFencedWithInvalidProducerEpochInInitProducerIdWithOlderClient
> kafka.server.KafkaApisTest.testStopReplicaRequestWithStaleBrokerEpochIsRejected
> kafka.server.KafkaApisTest.rejectJoinGroupRequestWhenStaticMembershipNotSupported
> kafka.server.KafkaApisTest.shouldRespondWithUnsupportedMessageFormatForBadPartitionAndNoErrorsForGoodPartition
> kafka.server.KafkaApisTest.rejectInitProducerIdWhenIdButNotEpochProvided
> kafka.server.KafkaApisTest.shouldRespondWithUnknownTopicOrPartitionForBadPartitionAndNoErrorsForGoodPartition
> kafka.server.KafkaApisTest.rejectOffsetCommitRequestWhenStaticMembershipNotSupported
> kafka.server.KafkaConfigTest.testFromPropsInvalid

@mumrah are any of these related to your changes?

**Comment by cmccabe** [comment]
thanks, @ijuma .

**Pull request merged**
