### PR TITLE
Merge trunk

### PR DESCRIPTION
**Pull request by mjsax**
Merge conflict on `tests/kafkatest/version.py`.

Keeping 7.7 for now as we did not yet bump to 7.8.

### CODE REVIEW

**Comment by jeffkbkim** [comment]
LGTM for my commits. build is failing though

**Comment by ditac** [comment]
LGTM for KAFKA-16083

**Comment by dajac** [comment]
LGTM for my commits.

**Review by adixitconfluent — APPROVED** [review]
LGTM, approving this PR as per conversation [here](https://confluent.slack.com/archives/C03F9DDV876/p1706193833157649?thread_ts=1705092047.836699&cid=C03F9DDV876)

**Review by lucasbru — APPROVED** [review]
LGTM for my commits

**Pull request merged**
