### PR TITLE
 Sync upstream changes

### PR DESCRIPTION
**Pull request by omkreddy**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by omkreddy** [comment]
There were no conflicts. It was a clean merge.

**Comment by stanislavkozlovski** [comment]
These LGTM. @omkreddy do you mind pulling all the new commits again? I'd like to get https://github.com/apache/kafka/commit/e4007a6408236d9b52b355fcf3c3a80fe5f570ff in as well as it looks very useful

**Comment by bob-barrett** [comment]
@omkreddy As a heads up, https://github.com/apache/kafka/commit/a97e55b83868ff786e740db55e73116f85456dcb renames `ImplicitLinkedHashSet` to `ImplicitLinkedHashCollection`. If we're using `ImplicitLinkedHashSet` anywhere in `ce-kafka` that isn't in AK, we'll have to change those usages as part of the merge.

**Comment by omkreddy** [comment]
@stanislavkozlovski @bob-barrett Thanks for the reviews. Merging to master

**Pull request merged**
