### PR TITLE
KC-578: Separate the state machine records apply into a different thread 

### PR DESCRIPTION
**Pull request by abbccdda**
Implement a separate thread to apply state machine records for better replication throughput.

Try to maintain synchronization on the log layer access.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by hachikuji** [comment]
Thanks for the patch. For the sake of discussion, let me suggest a slightly different direction. What if the Raft implementation didn't have to know about `ReplicatedStateMachine` or its semantics at all? Instead, we let `RaftClient` expose the APIs that are needed to implement a state machine on top of it. 

For example, suppose we have an interface like this:

```java
interface RaftClient {
  CompletableFuture<LogFetchInfo> read(LogOffsetMetadata offsetMetadata);
  CompletableFuture<OffsetAndEpoch> write(Records records);
  CompletableFuture<Void> shutdown(int timeoutMs);
}
```

Then the raft client is not responsible for pushing updates to the state machine. Instead, it is up to the state machine to pull them. For example, this allows for a direct apples-to-apples comparison with normal partition replication since we don't have to have a state machine at all.

Here is how I could imagine a typical state machine being written.

```java
class SimpleStateMachine {
   private final RaftClient client;

   private Thread readerThread = () -> {
     OffsetAndEpoch position = new OffsetAndEpoch(0, 0); 
     while (true) {
       Records records = client.read(position).get();
       synchronized {
         apply(records);
       }
   }

   public void updateSomeState(State newState) {
     synchronized {
       if (isValid(newState))
         client.write(toRecords(newState));
     }
   }
}
```

Since the state machine typically needs to know who is the leader, we could add an `ElectionListener` interface as well. Something like this:
```java
interface ElectionListener {
  void onElection(int leaderId, int epoch);
}
```

**Comment by jsancio** [comment]
re
```
interface RaftClient {
  CompletableFuture<LogFetchInfo> read(LogOffsetMetadata offsetMetadata);
  CompletableFuture<OffsetAndEpoch> write(Records records);
  CompletableFuture<Void> shutdown(int timeoutMs);
}
```
and
```
interface ElectionListener {
  void onElection(int leaderId, int epoch);
}
```

I'm not sure what should be interface but it would be nice to only have one style: either callback based `ElectionListener` or future based `RaftClient` in the example above. To change `ElectionListener` to the future style, we can:

1. Add `CompletableFuture<RaftState> raftState()` where `RaftState` has enough information to determine that the replica is a Leader, Follower, Candidate or Observer.

I think the state machine is interested in at least the following events/notifications:

1. Increase in the high-watermark - This is the `read` operation above.
1. New snapshot due to log truncation so that the state machine can load the snapshot. Maybe this can be an error in the `read` future and new function `readSnapshot` (or `findLatestSnapshot` and let the state machine read it however it wants).
1. Leader change: winning or losing election - This is `ElectionListener` in the API above.

I should also point out that it looks like a typical state machine will always have a pending `read` `CompletableFuture` meaning that once the previous read completes the state machine is interested in starting another `read`.

Note that some of the things I mentioned don't apply to the current PR but I am just thinking out loud on how it would work with the proposed API.

**Comment by hachikuji** [comment]
Hmm  the `raftState()` approach could also work, but it would be up to the state machine to poll it, which might be a little more awkward. Maybe in the state machine's fetch loop, it could also check if the node has become a leader and do any initialization logic there.

**Comment by jsancio** [comment]
> Hmm the `raftState()` approach could also work, but it would be up to the state machine to poll it, which might be a little more awkward. Maybe in the state machine's fetch loop, it could also check if the node has become a leader and do any initialization logic there.

Well, I suspect that the `NotSimpleStateMachine` :smile: will use [thenRunAsync](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html#thenRunAsync-java.lang.Runnable-java.util.concurrent.Executor-) or [runAfterEitherAsync](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html#runAfterEitherAsync-java.util.concurrent.CompletionStage-java.lang.Runnable-java.util.concurrent.Executor-) instead of performing a `.get()` like the `SimpleStateMachine` does.

**Comment by hachikuji** [comment]
Closing since we have a clearer idea about the direction of the API now.

**Pull request closed without merging**
