### PR TITLE
CONFLUENT: Sync from apache/kafka trunk to confluentinc/kafka master (10 August 2022)

### PR DESCRIPTION
**Pull request by ijuma**
Trivial conflict in gradle/dependencies.gradle due to the newer Netty version
in confluentinc/kafka.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by kpatelatwork** [comment]
Looks like the build is failing on 

> 08:22:26  FAILURE: Build failed with an exception.
08:22:26  
08:22:26  * What went wrong:
08:22:26  Execution failed for task ':core:compileScala'.
08:22:26  > Timeout waiting to lock zinc-1.6.1_2.12.15_8 compiler cache (/home/jenkins/.gradle/caches/7.5.1/zinc-1.6.1_2.12.15_8). It is currently in use by another Gradle instance.

**Comment by ijuma** [comment]
That's the 2.12 build, which seems to be flaky in this regard. I will restart it. The other one seems to be running still.

**Comment by kpatelatwork** [comment]
@ijuma in the rebuild 4 tests are failing and 3 seems unrelated but one of them is `QuorumControllerTest` and this PR has a big change in `QuorumController`. Could you please check?

**Comment by ijuma** [comment]
@kpatelatwork we should ask the metadata sme to help.

**Comment by ijuma** [comment]
Oh, I didn't realize the comment was for the ccs kafka merge. For this one, we won't block since the goal is for it to be a mirror of upstream for the most part.

**Review by kpatelatwork — APPROVED** [review]
LGTM @ijuma based on your comment about not being blocked on this in CCS kafka

**Pull request merged**
