### PR TITLE
Revert "KAFKA-10888: Sticky partition leads to uneven produce msg (#1…

### PR DESCRIPTION
**Pull request by vvcephei**
Doppelganger of https://github.com/apache/kafka/pull/12342 to revert the same commit from the ksqldb 0.27 release branch.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vvcephei** [comment]
FYI, in the main PR, there was a good suggestion to just swap back to the old default instead of reverting. I'm currently running a test to see if that helps before looking into this build failure.

**Comment by swist** [comment]
Tagging myself here because I'm unable to build rpms/debs until this is merged (due to a tooling bug)

**Comment by vvcephei** [comment]
The build failed with this error: `Cannot perform signing task ':connect:signMavenJavaPublication' because it has no configured signatory`

Do you know what that's about, @swist ?

**Comment by swist** [comment]
Looks like it's requiring some things to exist in the builder local gpg keyring, not sure where we normally get these from

**Comment by swist** [comment]
Looks like it's trying to sign because we match a very long ternary:
```
shouldSign = !skipSigning && !version.endsWith("SNAPSHOT") && !version.contains("-alpha") && !version.matches("[0-9]*\\.[0-9]*\\.[0-9]*-[0-9]*-(ccs|ce)")
```

but we don't really care, so I re-ran the PR build with signing turned off for now

**Comment by swist** [comment]
Skipping signing has passed but the status didn't update on the PR @vvcephei if you're happy with that, merge away!

**Review by swist — APPROVED** [review]

**Pull request closed without merging**
