### PR TITLE
Handling telemetry client errors

### PR DESCRIPTION
**Pull request by philipnee**
Handling telemetry errors and tests

### CODE REVIEW

**Comment by philipnee** [comment]
Moving https://github.com/confluentinc/kafka/pull/682 to this PR.

**Review by kirktrue — COMMENTED** [review]
LGTM. Can you double-check the linter doesn't complain about anything?

**Comment by kirktrue** [comment]
Yeah, there's at least one thing visible in the build:

```
11:38:09  [ant:checkstyle] [ERROR] /home/jenkins/workspace/confluentinc-pr_kafka_PR-685/clients/src/test/java/org/apache/kafka/clients/telemetry/DefaultClientTelemetryTest.java:152:9: 'while' is not followed by whitespace. [WhitespaceAfter]
```

**Comment by philipnee** [comment]
This is fixed, thanks @kirktrue

**Review by kirktrue — APPROVED** [review]

**Pull request merged**
