### PR TITLE
Merge AK 2.6 -> CCS 2.6, 7/13/2020

### PR DESCRIPTION
**Pull request by bdbyrne**
Merge branch '2.6' of https://github.com/confluentinc/kafka into 2.6

Merges AK 2.6 into CCS 2.6 as of 7/13/2020. Merge applied cleanly.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by bdbyrne** [comment]
Note single test failure is due to a current known flaky test: `kafka.admin.TopicCommandWithAdminClientTest.testDescribeUnderReplicatedPartitionsWhenReassignmentIsInProgress`

**Comment by sdanduConf** [comment]
@bdbyrne looks like there was a downstream build failure for ce-kafka-http-server (see the end of https://jenkins.confluent.io/job/Confluentinc%20Contributors/job/kafka/job/PR-360/1/execution/node/123/log/).  Not sure if its related to the change.

**Comment by bdbyrne** [comment]
> @bdbyrne looks like there was a downstream build failure for ce-kafka-http-server (see the end of https://jenkins.confluent.io/job/Confluentinc%20Contributors/job/kafka/job/PR-360/1/execution/node/123/log/). Not sure if its related to the change.

Looking now...

**Comment by bdbyrne** [comment]
I don't think this PR is the culprit because it affects ce-kafka 6.0.x, but I could also be mistaken as I'm confused where the disconnect is. What's happening is:

In ce-kafka 6.0.x, commit 6c3d445f270cf7ab8a60155691ccc41317739317 added a default interface implementation for method `Optional<KafkaHttpServer> provide(Map<String, Object> configuration, List<KafkaHttpServlet> applications)` - previously the derived class was required to provide the implementation.

In ce-kafka-http-server 6.0.x, there is no implementation of the above function. Which should be fine, however it must be using an older version of 6.0.x, prior to July 6th which is the above commit.

How do these two branches get versioned together? I would expect them to both pull from 6.0.x when building. As an aside, compiling the ce-kafka-http-server 6.0.x branch works locally for me.

**Comment by sdanduConf** [comment]
> I don't think this PR is the culprit because it affects ce-kafka 6.0.x, but I could also be mistaken as I'm confused where the disconnect is. What's happening is:
> 
> 
> 
> In ce-kafka 6.0.x, commit 6c3d445f270cf7ab8a60155691ccc41317739317 added a default interface implementation for method `Optional<KafkaHttpServer> provide(Map<String, Object> configuration, List<KafkaHttpServlet> applications)` - previously the derived class was required to provide the implementation.
> 
> 
> 
> In ce-kafka-http-server 6.0.x, there is no implementation of the above function. Which should be fine, however it must be using an older version of 6.0.x, prior to July 6th which is the above commit.
> 
> 
> 
> How do these two branches get versioned together? I would expect them to both pull from 6.0.x when building. As an aside, compiling the ce-kafka-http-server 6.0.x branch works locally for me.

Yeah you're right, a bit odd. Maybe the downstream projects list is incorrect. As you said, we shouldn't expect this to involve CcS Kafka

**Pull request closed without merging**
