### PR TITLE
CONFLUENT: Skip publishing for kafka-streams-upgrade-system-tests

### PR DESCRIPTION
**Pull request by vcrfxia**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vcrfxia** [comment]
Four test failures but otherwise the build looks good:
```
kafka.api.PlaintextEndToEndAuthorizationTest.testNoConsumeWithoutDescribeAclViaSubscribe(String).quorum=zk
kafka.api.SaslPlainSslEndToEndAuthorizationTest.testNoConsumeWithoutDescribeAclViaSubscribe(String).quorum=zk
kafka.api.SaslPlainSslEndToEndAuthorizationTest.testNoConsumeWithoutDescribeAclViaSubscribe(String).quorum=zk
kafka.network.ConnectionQuotasTest.testListenerConnectionRateLimitWhenActualRateAboveLimit()
```
Given that this PR only changes build.gradle, I think it's safe to say that these test failures are flaky.

**Comment by ijuma** [comment]
Thanks for the PR. If we don't need to publish these, should we submit this change upstream?

**Comment by vcrfxia** [comment]
Sure, happy to do that if it's preferable. I targeted this repo since I had thought there was urgency to unblocking these builds, while AK is not impacted. 

@mjsax can you confirm whether we want this change in AK as well? If so I'll switch to targeting AK directly.

**Comment by ijuma** [comment]
@vcrfxia We can go ahead with this repo first, if necessary. But good to upstream the change if it makes sense. If we don't need these projects published, it's a win all around to remove them. :)

**Review by ijuma — APPROVED** [review]
LGTM

**Comment by ijuma** [comment]
I merged this to master. It probably needs to be cherry-picked to older branches too.

**Comment by mjsax** [comment]
I thought we wanted to stop publishing javadocs and test jars? -- Does the system test Jenkins job not need to access those artifacts?

**Pull request merged**
