### PR TITLE
MERGE: Merge latest AK/3.3 to ccs-kafka/3.3 up to August 6

### PR DESCRIPTION
**Pull request by stanislavkozlovski**
This patch pulls the latest AK/3.3 changes.

Done via:
```
git pull ak 3.3
# where ak is the apache/kafka remote
```

No conflicts.

### CODE REVIEW

**Review by ijuma — APPROVED** [review]
LGTM

**Comment by stanislavkozlovski** [comment]
Yellow build. Failing tests:
```
[kafka.server.DynamicBrokerReconfigurationTest.testKeyStoreAlter(String).quorum=zk](https://jenkins.confluent.io/job/confluentinc-pr/job/kafka/job/PR-773/1/testReport/junit/kafka.server/DynamicBrokerReconfigurationTest/testKeyStoreAlter_String__quorum_zk/)
[kafka.server.DynamicBrokerReconfigurationTest.testKeyStoreAlter(String).quorum=kraft](https://jenkins.confluent.io/job/confluentinc-pr/job/kafka/job/PR-773/1/testReport/junit/kafka.server/DynamicBrokerReconfigurationTest/testKeyStoreAlter_String__quorum_kraft/)
[kafka.server.DynamicBrokerReconfigurationTest.testKeyStoreAlter(String).quorum=zk](https://jenkins.confluent.io/job/confluentinc-pr/job/kafka/job/PR-773/1/testReport/junit/kafka.server/DynamicBrokerReconfigurationTest/testKeyStoreAlter_String__quorum_zk_2/)
```

**Comment by stanislavkozlovski** [comment]
I started a rebuild in https://jenkins.confluent.io/job/confluentinc-pr/job/kafka/job/PR-773/2/

**Comment by stanislavkozlovski** [comment]
This test DynamicBrokerReconfigurationTest fails in AK too. I don't think we should block this merge on that

**Comment by stanislavkozlovski** [comment]
It was fixed in https://issues.apache.org/jira/browse/KAFKA-14122?jql=text%20~%20%22DynamicBrokerReconfigurationTest%22

**Pull request merged**
