### PR TITLE
CONFLUENT: Sync from apache/kafka 3.4 to confluentinc/kafka 3.4 (Mar 29)

### PR DESCRIPTION
**Pull request by Gerrrr**
Version related conflicts:

- 	gradle.properties
- 	streams/quickstart/java/pom.xml
- 	streams/quickstart/java/src/main/resources/archetype-resources/pom.xml
- 	streams/quickstart/pom.xml
- 	tests/kafkatest/__init__.py
- 	tests/kafkatest/version.py

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by Gerrrr** [comment]
Test failure `kafka.api.SslEndToEndAuthorizationTest.testNoConsumeWithoutDescribeAclViaSubscribe(String).quorum=zk` seems unrelated.

**Comment by omkreddy** [comment]
Can we add conflicts info to PR description. 
example: https://github.com/confluentinc/kafka/pull/772

**Comment by Gerrrr** [comment]
Done @omkreddy

**Review by omkreddy — APPROVED** [review]
LGTM

**Pull request merged**
