### PR TITLE
KAFKA-8245: Fix Flaky Test DeleteConsumerGroupsTest#testDeleteCmdAllGroups (#8032)

### PR DESCRIPTION
**Pull request by soondenana**
…roups (#8032)

Change unit tests to make sure the consumer group is in Stable state (i.e. consumers have completed joining the group)

(cherry picked from commit 413db69d41f22b10295782e38890cb0077d6e21c)

*More detailed description of your change,
if necessary. The PR title and PR message become
the squashed commit message, so use a separate
comment to ping reviewers.*

*Summary of testing strategy (including rationale)
for the feature or bug fix. Unit and/or integration
tests are expected for any behaviour change and
system tests should be considered for larger changes.*

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by ijuma** [comment]
Any reason why we're not making this change in Apache Kafka?

**Comment by ableegoldman** [comment]
It looks like the build failed previously but I can't see the results anymore, not sure what happened there?

**Comment by ableegoldman** [comment]
Nevermind, it looks like a flaky Streams test. I'll submit a ticket for it

**Comment by soondenana** [comment]
One test failure:
```
14:23:21  org.apache.kafka.streams.KafkaStreamsTest > testStateThreadClose FAILED
14:23:21      java.lang.AssertionError: Condition not met within timeout 10000. Thread never stopped.
14:23:21          at org.apache.kafka.test.TestUtils.waitForCondition(TestUtils.java:278)
14:23:21          at org.apache.kafka.streams.KafkaStreamsTest.testStateThreadClose(KafkaStreamsTest.java:204)
```
@ableegoldman is filing a ticket to track flakiness. However I need this PR to be in AK first. Going to move it there.

**Comment by soondenana** [comment]
AK PR: https://github.com/apache/kafka/pull/8234

Exactly same change as this PR (actually copied the test file from this PR to AK)

**Comment by ijuma** [comment]
We merged the change in AK. Closing.

**Pull request closed without merging**
