### PR TITLE
APPSEC-60: Upgrade org.apache.maven:apache-maven

### PR DESCRIPTION
**Pull request by xjin-Confluent**
Upgrade org.apache.maven:apache-maven.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by omkreddy — APPROVED** [review]
@xjin-Confluent Thanks for the PR. LGTM

**Comment by xjin-Confluent** [comment]
> @xjin-Confluent Thanks for the PR. LGTM

BTW,  what is this package used for? That seems to be a package from Apache Maven.

**Comment by omkreddy** [comment]
> > @xjin-Confluent Thanks for the PR. LGTM
> 
> BTW, what is this package used for? That seems to be a package from Apache Maven.

Yeah, I think Connect module is using one [utility class ](https://maven.apache.org/ref/3.6.1/maven-artifact/apidocs/org/apache/maven/artifact/versioning/DefaultArtifactVersion.html) for parsing and storing[ connector lib version. ](https://github.com/confluentinc/kafka/blob/master/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/PluginDesc.java#L28). We can copy the util class alone and remove the maven package usage if required.
cc @kkonstantine

**Comment by xjin-Confluent** [comment]
> > > @xjin-Confluent Thanks for the PR. LGTM
> > 
> > 
> > BTW, what is this package used for? That seems to be a package from Apache Maven.
> 
> Yeah, I think connect module is using [utility class ](https://maven.apache.org/ref/3.6.1/maven-artifact/apidocs/org/apache/maven/artifact/versioning/DefaultArtifactVersion.html) for parsing and storing[ connector lib version. ](https://github.com/confluentinc/kafka/blob/master/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/PluginDesc.java#L28). We can copy the util class and remove the maven package usage if required.
> cc @kkonstantine



> > > @xjin-Confluent Thanks for the PR. LGTM
> > 
> > 
> > BTW, what is this package used for? That seems to be a package from Apache Maven.
> 
> Yeah, I think connect module is using [utility class ](https://maven.apache.org/ref/3.6.1/maven-artifact/apidocs/org/apache/maven/artifact/versioning/DefaultArtifactVersion.html) for parsing and storing[ connector lib version. ](https://github.com/confluentinc/kafka/blob/master/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/PluginDesc.java#L28). We can copy the util class and remove the maven package usage if required.
> cc @kkonstantine

We'd prefer if this could be removed easily. Can you create a Jira and track the work?  For https://confluentinc.atlassian.net/browse/APPSEC-60, this PR is sufficient.

**Comment by omkreddy** [comment]
> We'd prefer if this could be removed easily. Can you create a Jira and track the work?
Pls check with #connect-eng team

**Comment by kkonstantine** [comment]
If this dependency is problematic, indeed we can consider copying the class. I'll create a Jira ticket tomorrow. Probably will be good to address in AK directly.

**Pull request merged**
