### PR TITLE
MINOR: Merge trunk

### PR DESCRIPTION
**Pull request by mjsax**
Need to resolve a merge-conflict in gradle/dependencies.gradle due to version bump of scalaLogging (cf 274eccf#diff-02b139e755ab0e27e0b0a6f9845843ef189116955cc340c49a4022587dbb2b52)

### CODE REVIEW

**Review by ijuma — APPROVED** [review]
I reviewed the `dependencies` file and that LGTM. If that's the only conflict, we can merge if the build looks good.

**Comment by mjsax** [comment]
@ijuma I think the failed tests are known to be flaky? Merge? Or rerun Jenkins?
```
kafka.network.DynamicConnectionQuotaTest.testDynamicListenerConnectionQuota()
kafka.network.DynamicConnectionQuotaTest.testDynamicListenerConnectionCreationRateQuota()
```

**Comment by ijuma** [comment]
Seems fine to merge.

**Comment by ijuma** [comment]
Please make sure not to use the GitHub merge button, you should push your branch to master directly.

**Pull request merged**
