### PR TITLE
AK->CCS Sync (Aug 4, 2020)

### PR DESCRIPTION
**Pull request by stanislavkozlovski**
There was a slight conflict in dependencies.gradle for the jackson and jacksonDatabind version.

I've kept confluentinc/kafka's pin to `jacksonDatabind=2.9.10.5` and ensure the databind library is pinned to it

### CODE REVIEW

**Comment by ijuma** [comment]
@stanislavkozlovski Looks like there is a spotBugs failure.

**Comment by stanislavkozlovski** [comment]
```
> Task :core:spotbugsMain FAILED
09:53:23  The following classes needed for analysis were missing:
09:53:23    org.apache.log4j.Logger
09:53:23    org.apache.log4j.Level
09:53:23    org.apache.log4j.LogManager
09:53:23  
09:53:23  FAILURE: Build failed with an exception.
09:53:23  
09:53:23  * What went wrong:
09:53:23  Execution failed for task ':core:spotbugsMain'.
09:53:23  > A failure occurred while executing com.github.spotbugs.internal.spotbugs.SpotBugsRunner
09:53:23     > SpotBugs rule violations were found. See the report at: file:///home/jenkins/workspace/entinc_Contributors_kafka_PR-379/core/build/reports/spotbugs/main.xml
09:53:23  
```

Running spotbugs locally, I get:
```
IS | Inconsistent synchronization of kafka.server.checkpoints.LazyOffsetCheckpointMap.checkpoint; locked 50% of time
-- | --
  | Bug type IS2_INCONSISTENT_SYNC (click for details)In class kafka.server.checkpoints.LazyOffsetCheckpointMapField kafka.server.checkpoints.LazyOffsetCheckpointMap.checkpointSynchronized 50% of the timeUnsynchronized access at OffsetCheckpointFile.scala:[line 85]Synchronized access at OffsetCheckpointFile.scala:[line 85]
```

We haven't changed anything related to that code path. All the latest changes in 2.4 are passing fine - https://github.com/confluentinc/kafka/commits/2.4

Weirdly enough, it's complaining that the same line is both synchronized and unsynchronized:
```
Unsynchronized access at OffsetCheckpointFile.scala:[line 85]
Synchronized access at OffsetCheckpointFile.scala:[line 85]
```
I think it may be because some paths in ReplicaManager are calling `new LazyOffsetCheckpoints` (which eventually reaches `OffsetCheckpointFile.scala:[line 85]`) with the `replicaStateChangeLock`, while some like ReplicaManager's initialization:
```
@volatile var highWatermarkCheckpoints: Map[String, OffsetCheckpointFile] = logManager.liveLogDirs.map(dir =>
    (dir.getAbsolutePath, new OffsetCheckpointFile(new File(dir, ReplicaManager.HighWatermarkFilename), logDirFailureChannel))).toMap
```
isn't calling it under a lock. Does that seem plausible to you @ijuma ?

**Comment by ijuma** [comment]
@stanislavkozlovski it's because of the `lazy val`. The bytecode involves synchronized when initializing and just a volatile read otherwise. I suggest you suppress the warning. I don't understand why this only started happening now though.

**Comment by stanislavkozlovski** [comment]
Thanks @ijuma. TIL. I added a suppression and comment as part of 4639e6cca371a136d86fac730de01a00c25ff378 and will merge on the next green build

**Comment by stanislavkozlovski** [comment]
Green build! Merging to 2.4

**Pull request merged**
