### PR TITLE
CONFLUENT: Sync from apache/kafka/trunk (25 May 2022)

### PR DESCRIPTION
**Pull request by stanislavkozlovski**
Conflicts:

- `Jenkinsfile`: stage('Build'). dropped ARM build and other changes that don't make sense for Confluent's version of
Jenkinsfile, as we only build the latest Scala version in PRs here

Full diff:
<details>
<summary>
NAME
</summary>
<p>

```

diff --cc Jenkinsfile
index e59183cbaa,7946f9a7fb..0000000000
mode 100755,100644..100755
--- a/Jenkinsfile
+++ b/Jenkinsfile
@@@ -35,111 -34,289 +35,231 @@@ def retryFlagsString(jobConfig) 
      else ""
  }
  
 -def doTest(env, target = "unitTest integrationTest") {
 -  sh """./gradlew -PscalaVersion=$SCALA_VERSION ${target} \
 -      --profile --no-daemon --continue -PtestLoggingEvents=started,passed,skipped,failed \
 -      -PignoreFailures=true -PmaxParallelForks=2""" + retryFlagsString(env)
 -  junit '**/build/test-results/**/TEST-*.xml'
 +def downstreamBuildFailureOutput = ""
 +def publishStep(String vaultSecret) {
 +    withVaultFile([["gradle/${vaultSecret}", "settings_file", "${env.WORKSPACE}/init.gradle", "GRADLE_NEXUS_SETTINGS"]]) {
 +        sh "./gradlewAll --init-script ${GRADLE_NEXUS_SETTINGS} --no-daemon uploadArchives"
 +    }
  }
  
 -def doStreamsArchetype() {
 -  echo 'Verify that Kafka Streams archetype compiles'
 -
 -  sh '''
 -    ./gradlew streams:publishToMavenLocal clients:publishToMavenLocal connect:json:publishToMavenLocal connect:api:publishToMavenLocal \
 -         || { echo 'Could not publish kafka-streams.jar (and dependencies) locally to Maven'; exit 1; }
 -  '''
 +def job = {
 +    // https://github.com/confluentinc/common-tools/blob/master/confluent/config/dev/versions.json
 +    def kafkaMuckrakeVersionMap = [
 +            "2.3": "5.3.x",
 +            "2.4": "5.4.x",
 +            "2.5": "5.5.x",
 +            "2.6": "6.0.x",
 +            "2.7": "6.1.x",
 +            "2.8": "6.2.x",
 +            "3.0": "7.0.x",
 +            "3.1": "7.1.x",
 +            "3.2": "7.2.x",
 +            "trunk": "master",
 +            "master": "master"
 +    ]
  
 -  VERSION = sh(script: 'grep "^version=" gradle.properties | cut -d= -f 2', returnStdout: true).trim()
 -
 -  dir('streams/quickstart') {
 -    sh '''
 -      mvn clean install -Dgpg.skip  \
 -          || { echo 'Could not `mvn install` streams quickstart archetype'; exit 1; }
 -    '''
 -
 -    dir('test-streams-archetype') {
 -      // Note the double quotes for variable interpolation
 -      sh """ 
 -        echo "Y" | mvn archetype:generate \
 -            -DarchetypeCatalog=local \
 -            -DarchetypeGroupId=org.apache.kafka \
 -            -DarchetypeArtifactId=streams-quickstart-java \
 -            -DarchetypeVersion=${VERSION} \
 -            -DgroupId=streams.examples \
 -            -DartifactId=streams.examples \
 -            -Dversion=0.1 \
 -            -Dpackage=myapps \
 -            || { echo 'Could not create new project using streams quickstart archetype'; exit 1; }
 -      """
 -
 -      dir('streams.examples') {
 -        sh '''
 -          mvn compile \
 -              || { echo 'Could not compile streams quickstart archetype project'; exit 1; }
 -        '''
 -      }
 +    if (config.nanoVersion && !config.isReleaseJob) {
 +        ciTool("ci-update-version ${env.WORKSPACE} kafka", config.isPrJob)
      }
 -  }
 -}
  
 -def tryStreamsArchetype() {
 -  try {
 -    doStreamsArchetype()
 -  } catch(err) {
 -    echo 'Failed to build Kafka Streams archetype, marking this build UNSTABLE'
 -    currentBuild.result = 'UNSTABLE'
 -  }
 -}
 +    stage("Check compilation compatibility with Scala 2.12") {
 +        sh "./gradlew clean assemble spotlessScalaCheck checkstyleMain checkstyleTest spotbugsMain " +
 +                 "--no-daemon --stacktrace -PxmlSpotBugsReport=true -PscalaVersion=2.12"
 +    }
  
  
 -pipeline {
 -  agent none
 -  
 -  options {
 -    disableConcurrentBuilds()
 -  }
 -  
 -  stages {
 -    stage('Build') {
 -      parallel {
 +    stage("Compile and validate") {
 +        sh "./gradlew clean assemble publishToMavenLocal spotlessScalaCheck checkstyleMain checkstyleTest spotbugsMain " +
 +                "--no-daemon --stacktrace -PxmlSpotBugsReport=true"
 +    }
  
 -        stage('JDK 8 and Scala 2.12') {
 -          agent { label 'ubuntu' }
 -          tools {
 -            jdk 'jdk_1.8_latest'
 -            maven 'maven_3_latest'
 -          }
 -          options {
 -            timeout(time: 8, unit: 'HOURS') 
 -            timestamps()
 -          }
 -          environment {
 -            SCALA_VERSION=2.12
 -          }
 -          steps {
 -            doValidation()
 -            doTest(env)
 -            tryStreamsArchetype()
 -          }
 +    if (config.publish) {
 +      stage("Publish to artifactory") {
 +        if (!config.isReleaseJob && !config.isPrJob) {
 +            ciTool("ci-push-tag ${env.WORKSPACE} kafka")
          }
  
 -        stage('JDK 11 and Scala 2.13') {
 -          agent { label 'ubuntu' }
 -          tools {
 -            jdk 'jdk_11_latest'
 -          }
 -          options {
 -            timeout(time: 8, unit: 'HOURS') 
 -            timestamps()
 -          }
 -          environment {
 -            SCALA_VERSION=2.13
 -          }
 -          steps {
 -            doValidation()
 -            doTest(env)
 -            echo 'Skipping Kafka Streams archetype test for Java 11'
 -          }
 -        }
 -
 -        stage('JDK 17 and Scala 2.13') {
 -          agent { label 'ubuntu' }
 -          tools {
 -            jdk 'jdk_17_latest'
 -          }
 -          options {
 -            timeout(time: 8, unit: 'HOURS') 
 -            timestamps()
 -          }
 -          environment {
 -            SCALA_VERSION=2.13
 -          }
 -          steps {
 -            doValidation()
 -            doTest(env)
 -            echo 'Skipping Kafka Streams archetype test for Java 17'
 -          }
 +        if (config.isDevJob) {
 +          publishStep('artifactory_snapshots_settings')
 +        } else if (config.isPreviewJob) {
 +          publishStep('artifactory_preview_release_settings')
          }
 +      }
 +    }
  
++<<<<<<< HEAD
 +    if (config.publish && config.isDevJob && !config.isReleaseJob && !config.isPrJob) {
 +        stage("Start Downstream Builds") {
 +            def downstreamBranch = kafkaMuckrakeVersionMap[env.BRANCH_NAME]
 +            config.downStreamRepos.each { repo ->
 +                build(job: "confluentinc/${repo}/${downstreamBranch}",
 +                    wait: false,
 +                    propagate: false
 +                )
 +            }
++=======
+         stage('ARM') {
+           options {
+             timestamps()
+           }
+           environment {
+             SCALA_VERSION=2.12
+           }
+           stages {
+             stage('Check ARM Agent') {
+               agent { label 'arm4' }
+               options {
+                 timeout(time: 5, unit: 'MINUTES')
+               }
+               steps {
+                 echo 'ARM ok'
+               }
+             }
+             stage('Run ARM Build') {
+               agent { label 'arm4' }
+               options {
+                 timeout(time: 2, unit: 'HOURS')
+               }
+               steps {
+                 doValidation()
+                 catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
+                   doTest(env, 'unitTest')
+                 }
+                 echo 'Skipping Kafka Streams archetype test for ARM build'
+               }
+             }
+           }
++>>>>>>> ak/trunk
          }
 +    }
 +
++<<<<<<< HEAD
 +    def runTestsStepName = "Step run-tests"
 +    def downstreamBuildsStepName = "Step cp-downstream-builds"
 +    def testTargets = [
 +        runTestsStepName: {
 +            stage('Run tests') {
 +                echo "Running unit and integration tests"
 +                sh "./gradlew unitTest integrationTest " +
 +                        "--no-daemon --stacktrace --continue -PtestLoggingEvents=started,passed,skipped,failed -PmaxParallelForks=4 -PignoreFailures=true" +
 +                        retryFlagsString(config)
 +            }
 +            stage('Upload results') {
 +                // Kafka failed test stdout files
 +                archiveArtifacts artifacts: '**/testOutput/*.stdout', allowEmptyArchive: true
  
 +                def summary = junit '**/build/test-results/**/TEST-*.xml'
 +                def total = summary.getTotalCount()
 +                def failed = summary.getFailCount()
 +                def skipped = summary.getSkipCount()
 +                summary = "Test results:\n\t"
 +                summary = summary + ("Passed: " + (total - failed - skipped))
 +                summary = summary + (", Failed: " + failed)
 +                summary = summary + (", Skipped: " + skipped)
 +                return summary;
 +            }
 +        },
 +        downstreamBuildsStepName: {
 +            echo "Building cp-downstream-builds"
 +            stage('Downstream validation') {
 +                if (config.isPrJob && config.downStreamValidate) {
 +                    downStreamValidation(config.nanoVersion, true, true)
 +                } else {
 +                    return "skip downStreamValidation"
 +                }
 +            }
++=======
+         stage('PowerPC') {
+           options {
+             timestamps()
+           }
+           environment {
+             SCALA_VERSION=2.12
+           }
+           stages {
+             stage('Check PowerPC Agent') {
+               agent { label 'ppc64le' }
+               options {
+                 timeout(time: 5, unit: 'MINUTES')
+               }
+               steps {
+                 echo 'PowerPC ok'
+               }
+             }
+             stage('Run PowerPC Build') {
+               agent { label 'ppc64le' }
+               options {
+                 timeout(time: 2, unit: 'HOURS')
+               }
+               steps {
+                 doValidation()
+                 catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
+                   doTest(env, 'unitTest')
+                 }
+                 echo 'Skipping Kafka Streams archetype test for PowerPC build'
+               }
+             }
+           }
+         }
+         
+         // To avoid excessive Jenkins resource usage, we only run the stages
+         // above at the PR stage. The ones below are executed after changes
+         // are pushed to trunk and/or release branches. We achieve this via
+         // the `when` clause.
+         
+         stage('JDK 8 and Scala 2.13') {
+           when {
+             not { changeRequest() }
+             beforeAgent true
+           }
+           agent { label 'ubuntu' }
+           tools {
+             jdk 'jdk_1.8_latest'
+             maven 'maven_3_latest'
+           }
+           options {
+             timeout(time: 8, unit: 'HOURS') 
+             timestamps()
+           }
+           environment {
+             SCALA_VERSION=2.13
+           }
+           steps {
+             doValidation()
+             doTest(env)
+             tryStreamsArchetype()
+           }
+         }
+ 
+         stage('JDK 11 and Scala 2.12') {
+           when {
+             not { changeRequest() }
+             beforeAgent true
+           }
+           agent { label 'ubuntu' }
+           tools {
+             jdk 'jdk_11_latest'
+           }
+           options {
+             timeout(time: 8, unit: 'HOURS') 
+             timestamps()
+           }
+           environment {
+             SCALA_VERSION=2.12
+           }
+           steps {
+             doValidation()
+             doTest(env)
+             echo 'Skipping Kafka Streams archetype test for Java 11'
+           }
++>>>>>>> ak/trunk
          }
 +    ]
  
 -        stage('JDK 17 and Scala 2.12') {
 -          when {
 -            not { changeRequest() }
 -            beforeAgent true
 -          }
 -          agent { label 'ubuntu' }
 -          tools {
 -            jdk 'jdk_17_latest'
 -          }
 -          options {
 -            timeout(time: 8, unit: 'HOURS') 
 -            timestamps()
 -          }
 -          environment {
 -            SCALA_VERSION=2.12
 -          }
 -          steps {
 -            doValidation()
 -            doTest(env)
 -            echo 'Skipping Kafka Streams archetype test for Java 17'
 -          }
 -        }
 -      }
 -    }
 -  }
 -  
 -  post {
 -    always {
 -      node('ubuntu') {
 -        script {
 -          if (!isChangeRequest(env)) {
 -            step([$class: 'Mailer',
 -                 notifyEveryUnstableBuild: true,
 -                 recipients: "dev@kafka.apache.org",
 -                 sendToIndividuals: false])
 -          }
 -        }
 -      }
 -    }
 -  }
 +    result = parallel testTargets
 +    // combine results of the two targets into one result string
 +    return result.runTestsStepName + "\n" + result.downstreamBuildsStepName
  }
 +
 +runJob config, job
 +echo downstreamBuildFailureOutput

```

</p>
</details>

### CODE REVIEW

**Comment by alok123t** [comment]
@ahuang98 can you take a look at the failed test, looks like you recently modified it

**Comment by stanislavkozlovski** [comment]
Failing tests
```
[Test Result](https://jenkins.confluent.io/job/confluentinc-pr/job/kafka/job/PR-720/1/testReport/) (3 failures )
[org.apache.kafka.connect.mirror.integration.MirrorConnectorsIntegrationBaseTest.testReplication()](https://jenkins.confluent.io/job/confluentinc-pr/job/kafka/job/PR-720/1/testReport/junit/org.apache.kafka.connect.mirror.integration/MirrorConnectorsIntegrationBaseTest/testReplication__/)
[integration.kafka.server.FetchRequestBetweenDifferentIbpTest.testControllerNewToOldIBP()](https://jenkins.confluent.io/job/confluentinc-pr/job/kafka/job/PR-720/1/testReport/junit/integration.kafka.server/FetchRequestBetweenDifferentIbpTest/testControllerNewToOldIBP__/)
[org.apache.kafka.controller.QuorumControllerTest.testUnregisterBroker()](https://jenkins.confluent.io/job/confluentinc-pr/job/kafka/job/PR-720/1/testReport/junit/org.apache.kafka.controller/QuorumControllerTest/testUnregisterBroker__/)
```
Yellow build, so it's ok to merge

**Comment by stanislavkozlovski** [comment]
Had to re-merge due to a new commit

**Comment by ableegoldman** [comment]
@stanislavkozlovski can this be merged now?

**Comment by alok123t** [comment]
build is yellow, failing test passed locally probably flaky. merging PR

**Pull request merged**
