### PR TITLE
Merge remote-tracking branch 'apache/trunk' into confluentinc/master

### PR DESCRIPTION
**Pull request by yyu1993**
No conflicts.

Downstream validation issue:
- TestUtils.scala: `getBrokerListStrFromServers()` was removed which causes downstream validation failure. This PR adds this method back with a deprecated annotation so that downstream components can be updated.

### CODE REVIEW

**Comment by ijuma** [comment]
Can you please describe the files with conflicts and how you fixed them?

**Comment by yyu1993** [comment]
> Can you please describe the files with conflicts and how you fixed them?

@ijuma I have updated the PR description.

**Comment by wcarlson5** [comment]
Do we have an ETA on getting the sync back up? This is blocking ksqlDB's release right now.

/cc @alapidas @tolgadur @ableegoldman @swist

**Comment by ableegoldman** [comment]
Looks like there were two test failures:
-[kafka.network.SocketServerTest.remoteCloseWithIncompleteBufferedReceive()](https://jenkins.confluent.io/job/confluentinc-pr/job/kafka/job/PR-666/4/testReport/junit/kafka.network/SocketServerTest/remoteCloseWithIncompleteBufferedReceive__/)
-[kafka.api.ConsumerBounceTest.testRollingBrokerRestartsWithSmallerMaxGroupSizeConfigDisruptsBigGroup()](https://jenkins.confluent.io/job/confluentinc-pr/job/kafka/job/PR-666/4/testReport/junit/kafka.api/ConsumerBounceTest/testRollingBrokerRestartsWithSmallerMaxGroupSizeConfigDisruptsBigGroup__/)

@yyu1993  Just to follow up on what Walker said, it's extremely important to the ksql team for this sync job to go through ASAP. Please consider this a high priority and let me know if there's anything we can do to help push this through. Thanks!

**Comment by ijuma** [comment]
@yyu1993 We don't usually make changes like that in ccs kafka. Which projects are using the removed method?

**Comment by yyu1993** [comment]
> @yyu1993 We don't usually make changes like that in ccs kafka. Which projects are using the removed method?

[Schema-Registry](https://github.com/confluentinc/schema-registry/blob/d8747f1f0c29e856c3af0e37aa20798ec3f8c937/core/src/test/java/io/confluent/kafka/schemaregistry/ClusterTestHarness.java#L134) and [Utility-Belt](https://github.com/confluentinc/common-docker/blob/e0328ba154692c9d8863a9e0a147f9246fdff2ca/utility-belt/src/test/java/io/confluent/admin/utils/EmbeddedKafkaCluster.java#L377) are using this method.

@hachikuji has proposed that we temporarily add the method in CCS so that downstream repos can have time to migrate to new methods. Then we will remove this method in CCS. Does this sound reasonable?

**Review by ijuma — APPROVED** [review]
@yyu1993 did a deeper search and there are 6 affected repositories. Given that, I am fine with merging what we have and doing the change concurrently.

**Comment by yyu1993** [comment]
> 

Rebuild is green and the two tests have passed.

**Pull request merged**
