### PR TITLE
Pick hotfixes

### PR DESCRIPTION
**Pull request by wcarlson5**
Cherry pick over 2 commits for ksql 0.26.1 hotfix

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by ijuma — APPROVED** [review]
LGTM for the non streams code, I'll leave it to someone else to review the latter.

**Review by ableegoldman — COMMENTED** [review]
@wcarlson5 were there any conflicts in Streams code/can you point me to where exactly in the file/code they occurred so I can just take a look at that and don't have to go through all of almost 3000 LOC... 😬

**Comment by wcarlson5** [comment]
@ableegoldman There were no conflicts after I cherrypicked the second PR

**Review by ijuma — APPROVED** [review]

**Review by arvindth — APPROVED** [review]
Approved for the change in CODEOWNERS.

**Pull request merged**
