### PR TITLE
Ak ccs merge 30 may

### PR DESCRIPTION
**Pull request by princepurohit**
Whenever there is version bumps we have to manually merge from ak to ccs.
It was clean merge except for version.py,
which had DEV_VERSION variable being bumped and hence a conflict.
This is essentially merge till 30 may

Going to run manually following command once few checks passes on jenkins
**git push origin ak-sync-30-may:master**

### CODE REVIEW

**Comment by princepurohit** [comment]
few tests failed on remote seems flaky local passes

image


------
Local Runs

image

image

image

**Review by danielgospodinow — APPROVED** [review]
LGTM, let's aim for a green build in the UI here. But If we can't get one, you can merge the branch since you've verified that the tests are just flaky ones.

**Comment by princepurohit** [comment]
And it seems this is timeout related , will confirm if all are for timeout
18:09:19          Caused by:
18:09:19          org.opentest4j.AssertionFailedError: Condition not met within timeout 120000. The connector or at least 1 of tasks are not running. ==> expected: <true> but was: <false>
18:09:19              at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
18:09:19              at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
18:09:19              at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
18:09:19              at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
18:09:19              at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:211)
18:09:19              at org.apache.kafka.test.TestUtils.lambda$waitForCondition$3(TestUtils.java:331)
18:09:19              at org.apache.kafka.test.TestUtils.retryOnExceptionWithTimeout(TestUtils.java:379)
18:09:19              at org.apache.kafka.test.TestUtils.waitForCondition(TestUtils.java:328)
18:09:19              at org.apache.kafka.test.TestUtils.waitForCondition(TestUtils.java:312)
18:09:19              at org.apache.kafka.test.TestUtils.waitForCondition(TestUtils.java:302)
18:09:19              at org.apache.kafka.connect.util.clusters.EmbeddedConnectClusterAssertions.assertConnectorAndAtLeastNumTasksAreRunning(EmbeddedConnectClusterAssertions.java:290)
18:09:19              ... 86 more
18:09:19

**Comment by princepurohit** [comment]
had 2nd run of tests
https://jenkins.confluent.io/job/Confluent%20Public%20Repo%20PR%20builder/job/kafka/job/PR-896/2/testReport/
this time more failures than first run

Tests seems flaky.
I will be going ahead and merge to ccs-kafka

**Pull request merged**
