### PR TITLE
Fix merge conflict

### PR DESCRIPTION
**Pull request by vvcephei**
### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by vvcephei** [comment]
The only conflict was the Jenkinsfile, which doesn't show up in the diff because there are no changes between this branch and `master`.

**Review by ijuma — APPROVED** [review]
LGTM if the downstream build passes.

**Comment by vvcephei** [comment]
Hey @andrewegel , I'm trying to get the trunk build working again. It's failing due to a merge conflict, which this PR fixes. There are test failures in this PR, but offhand, it seems good to at least commit the merge conflict fix and then deal with the test failures.

WDYT?

**Comment by andrewegel** [comment]
I'm more concerned about the downstream validation. See https://jenkins.confluent.io/job/Confluentinc%20Contributors/job/kafka/job/PR-544/2/flowGraphTable/ for the exact steps/stages/projects that are broken.

Example - there are build failures in:
* rest-utils: https://jenkins.confluent.io/job/Confluentinc%20Contributors/job/kafka/job/PR-544/2/execution/node/150/log/
* schema-registry: https://jenkins.confluent.io/job/Confluentinc%20Contributors/job/kafka/job/PR-544/2/execution/node/155/log/
* .. And many more

I would:
* Cross check against https://jenkins.confluent.io/view/CP%20Master%20Projects/ to see what have already been failing.
* If you can fix the downstream jobs in a compatible way, fix them now, re-run the PR job and get a pass.
* If you can't fix the downstream projects in a compatible way, well you'll have to drive the fix with the teams after you merge this in - I don't have any resources to ensure master's stability.

If your question is more around the kafka gradle unit/integ tests, those pass/failure rates are largely affected by what other jobs are running, and if you do enough re-runs you'll probably get all tests to pass across multiple runs.

In terms of whats right I leave that up to someone in cloud/ksql/streams because merging in known breaking changes affects their release velocity.

**Comment by vvcephei** [comment]
Thanks for that orientation, @andrewegel !

I've looked though several of those downstream failures, and they seem to be predominantly (if not universally) due to the fact that we are dropping deprecated members in the upcoming major (3.0) AK release. These members would only be dropped after being deprecated for at least a year. This will also certainly not be the only sync to get hung up on this problem, since I'd expect similar removals of deprecated members to roll in up until the 3.0 release.

Therefore, instead of taking the normal approach of fixing the downstream builds before merging, what I will do is notify #engineering to expect these kinds of failures for the next few months, and then just go ahead with the sync.

**Comment by vvcephei** [comment]
Ok, here is my broadcast: https://confluent.slack.com/archives/C038ZJ00P/p1617819685201900

Here's the text:

```
Hello all (esp @eng-managers), this is a broadcast message notifying all projects downstream of Kafka (which I guess is everyone) to watch out for compilation failures in their master branches over the next few months (starting today).
Apache Kafka is currently developing version 3.0.0, which (as a major-version release) will take the opportunity to drop APIs that have been deprecated for over a year.
If you have not been monitoring your builds for deprecation warnings, you may start to experience compilation errors like "cannot find symbol" and whatnot (see the end of this message for an example).
I expect the scope of these breakages to be large, so it would be intractable for the person who volunteers to fix the sync to personally fix all downstream build problems. Unfortunately, there's no good mechanism to map git repos to Slack channels to send direct warnings, either.
In lieu of those options, we will resort to just broadcasting such breakages here. Then, we will proceed with the sync.
The affected projects in this round are:
* rest-utils (https://jenkins.confluent.io/job/Confluentinc%20Contributors/job/kafka/job/PR-544/2/execution/node/150/log/)
* schema-registry (https://jenkins.confluent.io/job/Confluentinc%20Contributors/job/kafka/job/PR-544/2/execution/node/155/log/)
* kafka-rest (https://jenkins.confluent.io/job/Confluentinc%20Contributors/job/kafka/job/PR-544/2/execution/node/159/log/)
* ksql (https://jenkins.confluent.io/job/Confluentinc%20Contributors/job/kafka/job/PR-544/2/execution/node/167/log/)
* secret-registry (https://jenkins.confluent.io/job/Confluentinc%20Contributors/job/kafka/job/PR-544/2/execution/node/174/log/)
* confluent-security-plugins (https://jenkins.confluent.io/job/Confluentinc%20Contributors/job/kafka/job/PR-544/2/execution/node/178/log/)
* ce-kafka-http-server (https://jenkins.confluent.io/job/Confluentinc%20Contributors/job/kafka/job/PR-544/2/execution/node/182/log)
* ce-kafka-rest (https://jenkins.confluent.io/job/Confluentinc%20Contributors/job/kafka/job/PR-544/2/execution/node/186/log/)
* metadata-service (https://jenkins.confluent.io/job/Confluentinc%20Contributors/job/kafka/job/PR-544/2/execution/node/190/log/)
* blueway (https://jenkins.confluent.io/job/Confluentinc%20Contributors/job/kafka/job/PR-544/2/execution/node/194/log/)
* schema-registry-plugins (https://jenkins.confluent.io/job/Confluentinc%20Contributors/job/kafka/job/PR-544/2/execution/node/204/log/)
* confluent-cloud-plugins (https://jenkins.confluent.io/job/Confluentinc%20Contributors/job/kafka/job/PR-544/2/execution/node/208/log/)
---------------------------
PS: Here is an example of the failure you can expect:

[2021-04-07T04:41:50.691Z] [ERROR] /home/jenkins/workspace/entinc_Contributors_kafka_PR-544/rest-utils-master/core/src/test/java/io/confluent/rest/SslTest.java:[251,86] cannot find symbol
[2021-04-07T04:41:50.691Z] [ERROR]   symbol:   method value()
[2021-04-07T04:41:50.691Z] [ERROR]   location: variable metric of type org.apache.kafka.common.metrics.KafkaMetric

This failure is due to this removal: https://github.com/apache/kafka/commit/0018c3c0890407bb18788174c9c8fb584becd83e
You can see that the member in question was deprecated in version 1.0.0. I.e., *it has been deprecated for 3.5 years*.
```

I'd recommend that we send a similarly structured warning each time we merge a breaking sync. (cc @andrewegel , since you'll most likely get pinged any time this comes up).

**Comment by vvcephei** [comment]
Merged!

**Pull request merged**
