### PR TITLE
Merge AK trunk 04/12

### PR DESCRIPTION
**Pull request by vvcephei**
Resolved Jenkinsfile conflict by ignoring AK update.

### CODE REVIEW

**Review by ijuma — APPROVED** [review]
LGTM if the downstream build passes.

**Comment by vvcephei** [comment]
Thanks, @ijuma ! I'll keep an eye on the build.

**Comment by vvcephei** [comment]
Looks like just one downstream failure in blueway. I'll just go ahead and send a PR for it. (https://jenkins.confluent.io/job/confluentinc-pr/job/kafka/job/PR-546/1/execution/node/183/log/)

**Comment by vvcephei** [comment]
Ah, looks like there's already a fix in the pipeline: https://github.com/confluentinc/blueway/commit/cc74dfad133d0876093b5aa0261587a818ea55bb

**Pull request merged**
