### PR TITLE
Upgrade Jetty to 9.4.39.v20210325

### PR DESCRIPTION
**Pull request by xjin-Confluent**
Apply https://github.com/confluentinc/kafka/pull/547 on 2.4

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by niteshmor** [comment]
We should wait for tests to finish for this one. And triage whether any test failures are related to jetty. 
It's unlikely to result in problems, but I'll be more comfortable approving the pull request once we go through that process.

**Comment by xjin-Confluent** [comment]
09:22:34  FAILURE: Build failed with an exception.
09:22:34  
09:22:34  * What went wrong:
09:22:34  Execution failed for task ':streams:unitTest'.
09:22:34  > Process 'Gradle Test Executor 14' finished with non-zero exit value 134
09:22:34    This problem might be caused by incorrect test process configuration.
09:22:34    Please refer to the test execution section in the User Manual at https://docs.gradle.org/5.6.2/userguide/java_testing.html#sec:test_execution
09:22:34  
09:22:34  * Try:
09:22:34  Run with --info or --debug option to get more log output. Run with --scan to get full insights.
09:22:34  
09:22:34  * Exception is:
09:22:34  org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':streams:unitTest'.
09:22:34  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
09:22:34  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
09:22:34  	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
09:22:34  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:156)
09:22:34  	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
09:22:34  	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
09:22:34  	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
09:22:34  	at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
09:22:34  	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
09:22:34  	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
09:22:34  	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
09:22:34  	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
09:22:34  	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
09:22:34  	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
09:22:34  	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
09:22:34  	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
09:22:34  	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
09:22:34  	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
09:22:34  	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
09:22:34  	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
09:22:34  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
09:22:34  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
09:22:34  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
09:22:34  	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
09:22:34  	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
09:22:34  	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
09:22:34  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
09:22:34  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
09:22:34  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
09:22:34  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
09:22:34  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
09:22:34  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
09:22:34  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
09:22:34  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
09:22:34  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
09:22:34  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
09:22:34  	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
09:22:34  	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
09:22:34  Caused by: org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 14' finished with non-zero exit value 134
09:22:34  This problem might be caused by incorrect test process configuration.
09:22:34  Please refer to the test execution section in the User Manual at https://docs.gradle.org/5.6.2/userguide/java_testing.html#sec:test_execution
09:22:34  	at org.gradle.api.internal.tasks.testing.worker.ForkingTestClassProcessor.stop(ForkingTestClassProcessor.java:166)
09:22:34  	at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.endBatch(RestartEveryNTestClassProcessor.java:77)
09:22:34  	at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.stop(RestartEveryNTestClassProcessor.java:62)
09:22:34  	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
09:22:34  	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
09:22:34  	at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:30)
09:22:34  	at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:87)
09:22:34  	at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:36)
09:22:34  	at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:71)
09:22:34  	at org.gradle.internal.concurrent.InterruptibleRunnable.run(InterruptibleRunnable.java:42)
09:22:34  	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
09:22:34  	... 3 more



@omkreddy   Did not see anything specific about this Jetty upgrade. Any idea what's wrong?

**Comment by niteshmor** [comment]
I kicked off a build of `2.4` branch to see if the base branch itself has issues.

**Comment by xjin-Confluent** [comment]
https://confluent.slack.com/archives/C09EP1SS3/p1619452798115100

Downstream build failed for some reason: 
There are errors in the configuration of this machine. Please fix
the following errors and try again:
AWS Provider:
* A region must be specified via "region"


Ref: https://confluent.slack.com/archives/C09EP1SS3/p1619452798115100

**Review by andrewegel — APPROVED** [review]

**Pull request merged**
