### PR TITLE
Sync AK to ccs April 19

### PR DESCRIPTION
**Pull request by RamanVerma**
AK to ccs merge - April 19

**Conflicts Resolved**
Manually fixed minor merge conflicts caused due to this commit 
https://github.com/apache/kafka/commit/dc1ede8d89d0964783302e0da9ead7fa1d76fbe4

Please see this comment for list of conflicts that were resolved manually
https://github.com/confluentinc/kafka/pull/891#issuecomment-1528200373

**Testing**
Please see these comments for testing details
https://github.com/confluentinc/kafka/pull/891#issuecomment-1528268337
https://github.com/confluentinc/kafka/pull/891#issuecomment-1528308803

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by spena** [comment]
@RamanVerma This looks like a complete merge. Is it possible to include only the conflicted files? It'd be easier to review. I think the files that had a conflict were docs, properties and a couple of python tests?

**Comment by RamanVerma** [comment]
These were the conflicts that were resolved manually. Rest of the merge did not have any conflicts.
```
diff --cc gradle.properties
index d4bcddfd16,f8f0ddad87..0000000000
--- a/gradle.properties
+++ b/gradle.properties
@@@ -23,7 -23,7 +23,11 @@@ group=org.apache.kafk
  #  - streams/quickstart/pom.xml
  #  - streams/quickstart/java/src/main/resources/archetype-resources/pom.xml
  #  - streams/quickstart/java/pom.xml
++<<<<<<< HEAD
 +version=3.6.0-SNAPSHOT
++=======
+ version=7.5.0-0-ccs
++>>>>>>> b47b063ea0e31b60ad1de087541186e37f644736
  scalaVersion=2.13.10
  task=build
  org.gradle.jvmargs=-Xmx2g -Xss4m -XX:+UseParallelGC

diff --cc gradle/dependencies.gradle
index 0542eea470,3c8d4ae644..0000000000
--- a/gradle/dependencies.gradle
+++ b/gradle/dependencies.gradle
@@@ -144,7 -142,7 +144,11 @@@ libs +=
    argparse4j: "net.sourceforge.argparse4j:argparse4j:$versions.argparse4j",
    bcpkix: "org.bouncycastle:bcpkix-jdk15on:$versions.bcpkix",
    commonsCli: "commons-cli:commons-cli:$versions.commonsCli",
++<<<<<<< HEAD
 +  commonsValidator: "commons-validator:commons-validator:$versions.commonsValidator",
++=======
+   commonsCodec: "commons-codec:commons-codec:$versions.commonsCodec",
++>>>>>>> b47b063ea0e31b60ad1de087541186e37f644736
    easymock: "org.easymock:easymock:$versions.easymock",
    jacksonAnnotations: "com.fasterxml.jackson.core:jackson-annotations:$versions.jackson",
    jacksonDatabind: "com.fasterxml.jackson.core:jackson-databind:$versions.jacksonDatabind",

diff --cc streams/quickstart/java/pom.xml
index fc7436f1b3,7ff7ca80b4..0000000000
--- a/streams/quickstart/java/pom.xml
+++ b/streams/quickstart/java/pom.xml
@@@ -26,7 -26,7 +26,11 @@@
      <parent>
          <groupId>org.apache.kafka</groupId>
          <artifactId>streams-quickstart</artifactId>
++<<<<<<< HEAD
 +        <version>3.6.0-SNAPSHOT</version>
++=======
+         <version>7.5.0-0-ccs</version>
++>>>>>>> b47b063ea0e31b60ad1de087541186e37f644736
          <relativePath>..</relativePath>
      </parent>

diff --cc streams/quickstart/java/src/main/resources/archetype-resources/pom.xml
index 2a31d66c01,76758c1e72..0000000000
--- a/streams/quickstart/java/src/main/resources/archetype-resources/pom.xml
+++ b/streams/quickstart/java/src/main/resources/archetype-resources/pom.xml
@@@ -29,7 -29,7 +29,11 @@@

      <properties>
          <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
++<<<<<<< HEAD
 +        <kafka.version>3.6.0-SNAPSHOT</kafka.version>
++=======
+         <kafka.version>7.5.0-0-ccs</kafka.version>
++>>>>>>> b47b063ea0e31b60ad1de087541186e37f644736
          <slf4j.version>1.7.36</slf4j.version>
      </properties>

diff --cc streams/quickstart/pom.xml
index 9a8b617ac3,9dffb010cc..0000000000
--- a/streams/quickstart/pom.xml
+++ b/streams/quickstart/pom.xml
@@@ -22,7 -22,7 +22,11 @@@
      <groupId>org.apache.kafka</groupId>
      <artifactId>streams-quickstart</artifactId>
      <packaging>pom</packaging>
++<<<<<<< HEAD
 +    <version>3.6.0-SNAPSHOT</version>
++=======
+     <version>7.5.0-0-ccs</version>
++>>>>>>> b47b063ea0e31b60ad1de087541186e37f644736

      <name>Kafka Streams :: Quickstart</name>

diff --cc tests/kafkatest/__init__.py
index a52cc8ebbd,f45c276862..0000000000
--- a/tests/kafkatest/__init__.py
+++ b/tests/kafkatest/__init__.py
@@@ -21,5 -21,5 +21,10 @@@
  #
  # Instead, in development branches, the version should have a suffix of the form ".devN"
  #
++<<<<<<< HEAD
 +# For example, when Kafka is at version 1.0.0-SNAPSHOT, this should be something like "1.0.0.dev0"
 +__version__ = '3.6.0.dev0'
++=======
+ # For example, when Kafka is at version 1.0.0-0, this should be something like "1.0.0-0.dev0"
+ __version__ = '7.5.0-0.dev0'
++>>>>>>> b47b063ea0e31b60ad1de087541186e37f644736

diff --cc tests/kafkatest/version.py
index c31adc256b,d34bc7dfa4..0000000000
--- a/tests/kafkatest/version.py
+++ b/tests/kafkatest/version.py
@@@ -249,7 -249,3 +249,10 @@@ LATEST_3_4 = V_3_4_
  # 3.5.x versions
  V_3_5_0 = KafkaVersion("3.5.0")
  LATEST_3_5 = V_3_5_0
++<<<<<<< HEAD
 +
 +# 3.6.x versions
 +V_3_6_0 = KafkaVersion("3.6.0")
 +LATEST_3_6 = V_3_6_0
++=======
++>>>>>>> b47b063ea0e31b60ad1de087541186e37f644736
```

**Comment by RamanVerma** [comment]
Following tests failed in CI but passed when run on laptop

```
org.apache.kafka.connect.mirror.integration.MirrorConnectorsIntegrationTransactionsTest.testOneWayReplicationWithAutoOffsetSync()
org.apache.kafka.connect.storage.KafkaStatusBackingStoreFormatTest.putTopicStateRetriableFailure
kafka.network.SocketServerTest.testUnmuteChannelWithBufferedReceives()
org.apache.kafka.streams.processor.internals.tasks.DefaultTaskExecutorTest.shouldUnassignTaskWhenRequired()
```

**Comment by RamanVerma** [comment]
Manually triggered a run of Jenkins job `apache-kafka-test`
**CI will run kafka tests, system tests but not push to CK**
https://jenkins.confluent.io/job/apache-kafka-test/job/trunk/5583/

**Review by vincent81jiang — APPROVED** [review]
LGTM. thank you

**Review by mumrah — APPROVED** [review]
Metadata changes (from SCRAM work) look good.

**Comment by RamanVerma** [comment]
merged manually to preserve commit history. followed these steps
```
// this is my remote
git remote -vv
origin	git@github.com:confluentinc/kafka.git (fetch)
origin	git@github.com:confluentinc/kafka.git (push)

// Run following commands
git checkout master
git branch -vv // make sure master points to origin/master
git pull
git merge ak-ccs-merge-apr19
// Double check commit history 
git push origin master
```

**Pull request merged**
