### PR TITLE
Merge trunk

### PR DESCRIPTION
**Pull request by mjsax**
Resolving merge conflict for upstream version bump to 3.8-SNAPSHOT:
```
gradle.properties
streams/quickstart/java/pom.xml
streams/quickstart/java/src/main/resources/archetype-resources/pom.xml
streams/quickstart/pom.xml
tests/kafkatest/__init__.py
```

Plus one more conflict in `bin/kafka-server-stop.sh`:

```
<<<< HEAD
    PIDS=$(ps ax | grep ' kafka\.Kafka ' | grep java | grep -v grep | awk '{print $1}'| xargs)
====
    PIDS=$(ps ax | grep ' kafka\.Kafka ' | grep java | grep -v grep | awk '{print $1}')
    PIDS_SUPPORT=$(ps ax | grep -i 'io\.confluent\.support\.metrics\.SupportedKafka' | grep java | grep -v grep | awk '{print $1}')
>>>>
```

### CODE REVIEW

**Comment by rondagostino** [comment]
Thanks, @mjsax .  The `kafka-server-stop.sh` conflict resolution LGTM.

It seems you resolved the other conflicts related to the version bump in favor of this repo, not changing anything.  Do we want to include the version bump in this PR (similar to https://github.com/confluentinc/kafka/pull/979), or is the intention to do it separately?

**Comment by mjsax** [comment]
Thanks @rondagostino -- that's right. My understanding is that a version bump on `master` would happen independently. \cc @ijuma to confirm

**Review by rondagostino — APPROVED** [review]
LGTM.  Feel free to merge if you decide to do the version bump separately.

**Comment by mjsax** [comment]
Seems we don't have a 3.7 branch yet -- guess the version bump on `master` should only happen when we get 3.7 branch? i am not familiar with the process who/when 3.7 will/should be created. I assume, it will be part of CP 7.7 release (we are still working on 7.6 release right now).

**Pull request merged**
