### PR TITLE
EoS Message Format Cleanup and Polish

### PR DESCRIPTION
**Pull request by hachikuji**
Major changes:

1. `LogEntry` is now an interface. The old implementation is confined in `OldLogEntry` and `Record`. The only fields accessible from `LogEntry` are those from the message set header. Similarly the only fields accessible from `LogRecord` are those from the message itself.
2. `OldLogEntry` implements both `LogEntry` and `LogRecord`, which makes some intuitive sense since there was no prior distinction between the structure of entries and records.
3. I removed `deepEntries` from `LogEntry` and updated all the code to use `records` instead. This allowed me to also remove `RecordsIterator` (though I still needed the deep iteration logic which was moved into `OldLogEntry`).

### CODE REVIEW

**Comment by hachikuji** [comment]
cc @guozhangwang @apurvam

**Comment by apurvam** [comment]
I had a quick scan over this. What would help in general --and especially for the review-- is some documentation in the code describing the new relationship between `LogEntry`, `LogRecord`, `Records`,  and their relationship to the structure of the serialized bytes sent over the wire and written to disk.

This sort of javadoc would help in the future as well: the message structure has thus far not been documented well, and that hurts newbies. 

Also, what happened to `ShallowLogEntry`.

**Comment by hachikuji** [comment]
Sure, I can add some documentation. I would _love_ to change the name of `FileRecords` and `MemoryRecords` since it makes the hierarchy seem convoluted and confusing. Ideally, the root should be a log, which contains many log entries, each of which contains many log records. So

`Log` -> `LogEntry` -> `LogRecord`

And that should be it. Instead we have:

`Records` -> `LogEntry` -> `LogRecord`

`ShallowLogEntry` was renamed to `MutableLogEntry`. The name "shallow" is no longer meaningful since there are _only_ shallow log entries.

**Comment by hachikuji** [comment]
Moved to #125

**Pull request closed without merging**
