### PR TITLE
Merge AK Trunk

### PR DESCRIPTION
**Pull request by vvcephei**
Merges with AK trunk just before the bump to 2.9 (https://github.com/confluentinc/kafka/pull/503)

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by rajinisivaram** [comment]
@vvcephei Were there merge conflicts that needed to be manually resolved that need review? The PR build seems to have failed, so restarted that.

**Comment by vvcephei** [comment]
Thanks, @rajinisivaram !

No, this was the commit immediately before the bump, and it was clean.
https://github.com/confluentinc/kafka/pull/503 did have conflicts.

**Review by rajinisivaram — APPROVED** [review]
@vvcephei Thanks for the PR, LGTM

**Comment by vvcephei** [comment]
Thanks, @rajinisivaram ! Do you mind merging it? I am not an "authorized user."

**Pull request merged**
