### PR TITLE
Merge 2.9 bump

### PR DESCRIPTION
**Pull request by vvcephei**
Fixes the merge conflicts from my bump of AK to 2.9.0-SNAPSHOT.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by rajinisivaram — APPROVED** [review]
@vvcephei Thanks for the PR, LGTM. Left a note on PR #504.

**Comment by vvcephei** [comment]
The last build got cancelled by Jenkins. I re-ran it.

**Review by andrewegel — CHANGES_REQUESTED** [review]
For now AK can be set to 2.9, but the next CP will be `7.0` - so you will have to update all `6.3` version updates with `7.0`

**Comment by andrewegel** [comment]
I'll take this task over in https://github.com/confluentinc/kafka/pull/519

**Pull request closed without merging**
