### PR TITLE
MINOR: Upgrade jackson-databind version

### PR DESCRIPTION
**Pull request by niteshmor**
v2.9.10.5 fixes 16 critical/high CVEs present in v2.9.10.3

### CODE REVIEW

**Comment by ijuma** [comment]
I thought we were planning to upgrade 2.4 to 2.10.x.

**Comment by niteshmor** [comment]
> I thought we were planning to upgrade Jackson in the 2.4 branch to 2.10.x.

Yes, that would have been nice. But the driving factor for that other pull request was an issue present in jackson 2.10.2 with a `dataformat-yaml`. On a closer look, it turns out that kafka by itself doesn't use the affected class. So that pull request went fairly stale.

The driving factor for this particular pull request is upcoming 5.4.x release, which brings in lots of CVEs because of kafka's use of `jackson-databind:.9.10.3`.

I should mention that there is an oddity that I noticed in how versions are setup for jackson in `confluentinc/kafka`
```
2.1  jackson: "2.9.10",
2.2  jackson: "2.10.0",
2.3  jackson: "2.10.0",
2.4  jackson: "2.9.10",     # AK uses 2.10.0 for jackson
2.5  jackson: "2.10.2",
2.6  jackson: "2.10.2",
```

**Comment by ijuma** [comment]
Yeah, that oddity is why we want to upgrade this to Jackson 2.10.x. There was an issue with Avro, but I believe @rayokota fixed that by upgrading it.

**Comment by niteshmor** [comment]
Ah, I see. Just making sure that's not an accident. :)

**Pull request merged**
