### PR TITLE
KAFKA-2892: Consumer Docs Use Wrong Method

### PR DESCRIPTION
**Pull request by eljefe6a**
The KafkaConsumer docs use a non-existent method for assigning partitions (`consumer.assign`).

The JavaDocs show as:
```
String topic = "foo";
TopicPartition partition0 = new TopicPartition(topic, 0);
TopicPartition partition1 = new TopicPartition(topic, 1);
consumer.assign(partition0);
consumer.assign(partition1);
```

Should be:
```
String topic = "foo";
TopicPartition partition0 = new TopicPartition(topic, 0);
TopicPartition partition1 = new TopicPartition(topic, 1);
consumer.assign(Arrays.asList(partition0));
consumer.assign(Arrays.asList(partition1));
```

### CODE REVIEW

**Comment by ewencp** [comment]
Good catch. `assign` doesn't actually allow incremental assignment though:

```
Manually assign a list of partition to this consumer. This interface does not allow for incremental assignment and will replace the previous assignment (if there is one).
```

It'd need to be `consumer.assign(Arrays.asList(partition0, partition1))`.

**Comment by eljefe6a** [comment]
@ewencp Updated.

**Comment by ewencp** [comment]
LGTM

**Comment by gwenshap** [comment]
LGTM, but I'm wondering if @eljefe6a didn't mean to submit this PR to Apache Kafka and not the Confluent copy?

**Comment by eljefe6a** [comment]
@gwenshap  That's correct. I just found out that you can't fork repos with different sources.

**Comment by gwenshap** [comment]
ah, so because you already forked confluent's fork you can't fork apache?

**Comment by eljefe6a** [comment]
Yup http://stackoverflow.com/questions/9644046/how-to-change-the-source-of-a-github-fork

**Comment by gwenshap** [comment]
so, afaik, all of us here do "apache first" flow - we have a fork of apache kafka, we do PRs there and we update confluent kafka from apache.

That said, if you don't want to go to the trouble of creating a new fork and re-doing your work, we can probably merge it here and do a PR to apache Kafka from here.

**Comment by ijuma** [comment]
This was submitted to the Apache repo and merged some time ago.

**Pull request closed without merging**
