### PR TITLE
Merge remote-tracking branch 'ak-upstream/trunk' into AK_CCS_Mar_07_22

### PR DESCRIPTION
**Pull request by soondenana**
Conflict in Jenkinsfile from AK commit: [bbb2dc54a0f45bc5455f22a0671adde206dcfa29](https://github.com/apache/kafka/commit/bbb2dc54a0f4)  from PR: [11833](https://github.com/apache/kafka/pull/11833)

I have dropped the change as it doesn't pertain to CCS.

All other files merged cleanly.

### CODE REVIEW

**Review by ijuma — APPROVED** [review]
LGTM if Jenkins is green.

**Comment by soondenana** [comment]
After the merge, following 3 tests are failing:

```
kafka.admin.LeaderElectionCommandTest.[1] Type=Raft, Name=testElectionResultOutput, Security=PLAINTEXT
kafka.api.PlaintextProducerSendTest.testSendWithInvalidCreateTime()
kafka.server.ProduceRequestTest.testProduceWithInvalidTimestamp()
```

I will take a look at this tomorrow.

**Comment by soondenana** [comment]
We will need to merge again as AK trunk is broken. We need https://github.com/apache/kafka/pull/11853, I will wait for that to get merged.

**Comment by soondenana** [comment]
Only one test failed after recently pullin AK trunk

> kafka.admin.DescribeConsumerGroupTest.testDescribeOffsetsOfExistingGroupWithNoMembers()

Ran it locally and it passes, so going to treat it flaky and merge the PR.

**Pull request merged**
