### PR TITLE
AK to Confluent 2.4 sync for Oct 29, 2019

### PR DESCRIPTION
**Pull request by mumrah**
There were no conflicts. One change was needed in KafkaUtilites for a change class name (PartitionReplicaAssignment -> ReplicaAssignment)

### CODE REVIEW

**Comment by ijuma** [comment]
2 tests failed:
> kafka.admin.ReassignPartitionsClusterTest.znodeReassignmentShouldOverrideApiTriggeredReassignment
> kafka.api.PlaintextConsumerTest.testFetchInvalidOffset

**Comment by ijuma** [comment]
Build restarted, thanks to @sdanduConf

**Comment by ijuma** [comment]
Different set of failures this time:

> kafka.api.SaslSslAdminClientIntegrationTest.testCreateTopicsResponseMetadataAndConfig
> org.apache.kafka.streams.integration.StreamTableJoinIntegrationTest.testInner[caching enabled = true]

**Comment by mumrah** [comment]
Manually ran downstream muckrake build, which passed

**Pull request merged**
